### PR TITLE
Make constructor throw on invalid ports.

### LINKED ISSUE #344: Port is not validated the same when constructing URI as when using uri.port() method
```js
// The following works (when I think it shouldn't)
var uri = URI('http://example.com:robots.txt');

// Even this works
console.log(uri.port()); // Will output 'robots.txt'

// This does not work however...
var uri = URI('http://example.com');

// ...since this will (correctly) throw an error
uri.port('robots.txt');
```

Could we look into adding the same validation of the URI port when constructing URI instances from strings as we have when calling the `uri.port` method?

### PR DESCRIPTION
**Pull request by konstantinblaesi**
This makes the behaviour consistent with port().

Fixes #344

### CODE REVIEW

File: src/URI.js [hunk 1]
```diff
@@ -575,6 +575,10 @@
       string = '/' + string;
     }
 
+    if (parts.port) {
```
Comment (rodneyrehm) [inline src/URI.js]: this change should be covered by a test for the constructor (`test/test.js`, line 132)

Comment (konstantinblaesi) [inline src/URI.js]: I added a negative and a positive test, one for each case. Is that enough?

File: src/URI.js [hunk 2]
```diff
@@ -524,6 +524,8 @@
     // what's left must be the path
     parts.path = string;
 
+    URI.basicValidation(parts);
```
Comment (rodneyrehm) [inline src/URI.js]: The validation should probably be done in [`URI.parseHost()`](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L530)? maybe [`URI#hostname()`'s validation](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L1307) can be moved there, too?

File: src/URI.js (hunk 1 above)
Comment (rodneyrehm) [inline src/URI.js]: I don't think we need a positive test case, there are plenty of those :)

File: src/URI.js [hunk 3]
```diff
@@ -1031,6 +1037,22 @@
     }
   };
 
+  URI.ensureValidPort = function(v) {
+    if (v.match(/[^0-9]/)) {
+      throw new TypeError('Port "' + v + '" contains characters other than [0-9]');
+    }
+  };
+
+  URI.basicValidation = function(parts) {
```
Comment (rodneyrehm) [inline src/URI.js]: should this be called `ensureValidHostname()`?

File: src/URI.js [hunk 4]
```diff
@@ -1031,6 +1037,22 @@
...
+    var hasProtocol = !parts.protocol;
+    var isHttpOrHttps = hasProtocol && (parts.protocol.indexOf('http') !== -1);
+    var hasHostname = !parts.hostname;
+
+    if (isHttpOrHttps && !hasHostname) {
+      throw new TypeError('Hostname cannot be empty, if protocol is http(s)');
```
Comment (rodneyrehm) [inline src/URI.js]: this is true of any protocol, even the empty protocol `://hostname/path`

File: src/URI.js (hunk 1 above)
Comment (konstantinblaesi) [inline src/URI.js]: Ok, I've removed the positive testcase, improved the port validation code and 3 negative tests in total.

File: src/URI.js (hunk 2 above)
Comment (konstantinblaesi) [inline src/URI.js]: I've created and called the method this way because I wanted to put some validation there that isn't just about a specific part of the url but about a combination such as protocol, hostname, path.

**Comment by konstantinblaesi** [comment]
Looks like rewording/editing/amending commits isn't a good idea for implementing requested changes. It's probably better to add new commits and do the squashing/merging when it's ready to merge?

File: src/URI.js (hunk 3 above)
Comment (konstantinblaesi) [inline src/URI.js]: I put it here because I just wanted to prevent "http:///" being a valid input for the constructor. Since I am not only checking the hostname, but also protocol and path I extracted it into it's own function.

File: src/URI.js (hunk 4 above)
Comment (konstantinblaesi) [inline src/URI.js]: I've updated the code because apparently my single negation was wrong anyways.

File: src/URI.js [hunk 5]
```diff
@@ -1024,11 +1034,41 @@
...
+        valid = true;
       }
     }
+
+    if (!valid) {
+      throw new TypeError('Port "' + v + '" is not a valid port');
+    }
+  };
+
+  URI.basicValidation = function(parts) {
```
Comment (rodneyrehm) [inline src/URI.js]: this is not limited to HTTP/S, but also applies to ssh, ftp, and many more. Maybe we should create `URI.hostProtocols` analoguous to `URI.defaultPorts`? The name of this function should be similar to the property, so `URI.ensureHostProtocol()` or something like that? either way, `basic` is not a thing in URLs, so the term is really irritating.

File: src/URI.js [hunk 6]
```diff
@@ -1024,11 +1034,41 @@
...
       }
-
       if (punycode.toASCII(v).match(URI.invalid_hostname_characters)) {
-        throw new TypeError('Hostname "' + v + '" contains characters other than [A-Z0-9.-]');
+        throw new TypeError('Hostname "' + v + '" contains characters other than [A-Z0-9.:-]');
+      }
+    }
+  };
+
+  URI.ensureValidPort = function(v) {
```
Comment (rodneyrehm) [inline src/URI.js]: could be simplified to

```js
URI.ensureValidPort = function(v) {
  if (!v) {
    return;
  }

  var port = Number(v);
  if (Number.isInteger(port) && (port > 0) && (port < 65536)) {
    return;
  }

  throw new TypeError('Port "' + v + '" is not a valid port');
};
```

Comment (konstantinblaesi) [inline src/URI.js]: done

File: src/URI.js (hunk 5 above)
Comment (konstantinblaesi) [inline src/URI.js]: Are you suggesting to reject all URLs of the form protocol:/// no matter what the protocol is?

Comment (rodneyrehm) [inline src/URI.js]: sorry for the delay… no, I'm suggesting putting the protocols for which we require a hostname into a map on `URI`, like it's done for `URI.`defaultPorts. That would allow anyone to easily add the protocols they want validated the same way

Comment (konstantinblaesi) [inline src/URI.js]: @rodneyrehm What do you think, is this ready to merge?

**Comment by rodneyrehm** [comment]
thanks for your effort! released as [v1.18.11](https://github.com/medialize/URI.js/releases/tag/v1.18.11) :)

**Comment by rodneyrehm** [comment]
Hey @konstantinblaesi,

since the introduction of hostname verification in [v1.18.11](https://github.com/medialize/URI.js/releases/tag/v1.18.11) we've seen a few compatibility problems: #352, #354, #355. 

I'm considering the rollback of your change - unless you have a better idea?

**Comment by rodneyrehm** [comment]
As the hostname validation caused some kerfuffle I've decided to make this feature *opt-in*, thereby returning to the previous default behavior of v1.18.10. As of [v1.19.0](https://github.com/medialize/URI.js/releases/tag/v1.19.0) you can activate hostname validation globally by setting `URI.preventInvalidHostname = true`, or on an instance by calling `.preventInvalidHostname(true)`.

I'm sorry for the confusion, inconvenience caused by the original change and the delayed rectification.
